@startuml
!include ./Game/CharacterController2D.puml
!include ./Game/Door.puml
!include ./Game/Player.puml
!include ./Lib/ResourceFinder.puml
!include ./Lib/TypeReference.puml
!include ./Lib/Timer.puml
!include ./test/TestBtnLoad.puml
!include ./test/Transporter.puml
!include ./test/TestBtnSave.puml
!include ./test/ChallengeActivator.puml
!include ./Game/StateManagementGame/GameStateLoadingScreen.puml
!include ./Game/StateManagementGame/StateManagerGame.puml
!include ./Game/StateManagementGame/GameStatePlay.puml
!include ./Game/StateManagementGame/GameStateMessage.puml
!include ./Game/StateManagementGame/GameStateChallenge.puml
!include ./Game/StateManagementGame/GameStateInventory.puml
!include ./Game/StateManagementGame/BaseGameState.puml
!include ./Game/Character/CharacterData.puml
!include ./Game/Character/CharacterSaveData.puml
!include ./Game/Character/Character.puml
!include ./Game/Character/CharacterSelector.puml
!include ./Game/Singletons/ManagerUI.puml
!include ./Lib/Input/test.puml
!include ./Lib/Input/InputAction.puml
!include ./Lib/Input/InputManager.puml
!include ./Lib/StateManagement/StateObject.puml
!include ./Lib/StateManagement/AbstractStateManager.puml
!include ./Lib/StateManagement/BaseState.puml
!include ./Lib/StateManagement/AbstractStateStack.puml
!include ./Lib/Persistence/SaveLoadSystem.puml
!include ./Lib/Persistence/GameData.puml
!include ./Lib/EventSystem/EventListener.puml
!include ./Lib/EventSystem/EventChannel.puml
!include ./Lib/Extensions/NodeExtensions.puml
!include ./Lib/Extensions/LinqExtensions.puml
!include ./Lib/Extensions/VectorExtensions.puml
!include ./Lib/Extensions/NodeSearchExtensions.puml
!include ./Lib/Easings/EasingDerivatives.puml
!include ./Lib/Easings/Easings.puml
!include ./Game/UI/MVC_Fade/FadeModel.puml
!include ./Game/UI/MVC_Fade/FadeView.puml
!include ./Game/UI/MVC_Fade/FadeController.puml
!include ./Game/UI/Carrousel/Carrousel.puml
!include ./Game/UI/Carrousel/CarrouselValue.puml
!include ./Game/UI/Carrousel/CarrouselController.puml
!include ./Game/Systems/StatModifiers/BaseStats.puml
!include ./Game/Systems/StatModifiers/Stats.puml
!include ./Game/Systems/StatModifiers/StatModifier.puml
!include ./Game/Systems/StatModifiers/StatsMediator.puml
!include ./Game/Systems/SaveLoadSystem/SaveLoadManager.puml
!include ./Game/Systems/SaveLoadSystem/MyGameData.puml
!include ./Game/Systems/Challenges/ChallengeValue.puml
!include ./Game/Systems/Challenges/MathChallenge.puml
!include ./Game/Systems/Abilities/ModifierEffect.puml
!include ./Game/Systems/Abilities/AttributeModifierEffect.puml
!include ./Game/Systems/Abilities/StatModifierEffect.puml
!include ./Game/Systems/Abilities/Ability.puml
!include ./Game/Systems/Abilities/AbilityEffect.puml
!include ./Game/Systems/Abilities/BaseAbilityEffect.puml
!include ./Game/Systems/QuestSystem/QuestManagerSaveData.puml
!include ./Game/Systems/QuestSystem/QuestManager.puml
!include ./Game/Systems/QuestSystem/Quest.puml
!include ./Game/Systems/QuestSystem/QuestObjectiveActor.puml
!include ./Game/Systems/QuestSystem/QuestEventListener.puml
!include ./Game/Systems/QuestSystem/QuestObjective.puml
!include ./Game/Systems/QuestSystem/QuestEventChannel.puml
!include ./Game/Character/Attributes/AttributeModifier.puml
!include ./Game/Character/Attributes/Attributes.puml
!include ./Game/Character/Attributes/AttributeMediator.puml
!include ./Game/UI/MVC_Challenges/View/ChallengeUI.puml
!include ./Game/UI/MVC_Challenges/View/ChallengeUIFactory.puml
!include ./Game/UI/MVC_Challenges/View/ChallengeUIStrategy.puml
!include ./Game/UI/MVC_Challenges/View/ChallengeView.puml
!include ./Game/UI/MVC_Challenges/Controller/ChallengeController.puml
!include ./Game/UI/MVC_Challenges/Model/ChallengeModel.puml
!include ./Game/UI/MVC_CharacterSelection/View/CharacterSelectionView.puml
!include ./Game/UI/MVC_CharacterSelection/Controller/CharacterSelectionController.puml
!include ./Game/UI/MVC_CharacterSelection/Model/CharacterSelectionModel.puml
!include ./Game/UI/MVC_Inventory/View/InventoryView.puml
!include ./Game/UI/MVC_Inventory/Controller/InventoryController.puml
!include ./Game/UI/MVC_Inventory/Model/InventoryModel.puml
!include ./Game/UI/MVC_ActionsMenu/View/ActionsMenuView.puml
!include ./Game/UI/MVC_ActionsMenu/Controller/ActionsMenuController.puml
!include ./Game/UI/MVC_ActionsMenu/Model/ActionsMenuModel.puml
!include ./Game/UI/MVC_ActionsMenu/Model/ButtonData.puml
!include ./Game/UI/MVC_Messages/View/Notification.puml
!include ./Game/UI/MVC_Messages/View/MessageView.puml
!include ./Game/UI/MVC_Messages/Controller/MessageController.puml
!include ./Game/UI/MVC_Messages/Model/MessageModel.puml
!include ./Game/UI/MVC_Challenges/View/ChallengeUIElements/ChallengeParamInput.puml
!include ./Game/UI/MVC_Challenges/View/ChallengeUIElements/ChallengeValueInput.puml
!include ./Game/UI/MVC_Challenges/View/ChallengeUIElements/ChallengeSelectOption.puml
!include ./Game/UI/MVC_Challenges/View/ChallengeUIElements/ChallengeValueView.puml
!include ./Game/UI/MVC_Challenges/View/ChallengeUIElements/ChallengeSelect.puml
!include ./Game/UI/MVC_Challenges/View/ChallengeUIElements/CombinationLock/CombinationLockValue.puml
!include ./Game/UI/MVC_Challenges/View/ChallengeUIElements/CombinationLock/CombinationLockWheel.puml
@enduml
