name: My Config
version: 1.0.0
schema: v1
mcpServers:
  - name: filesystem
    command: npx
    args:
      - -y
      - "@modelcontextprotocol/server-filesystem"
      - ./
    cwd: /home/syndias/Projects/TnT/Edugame-Godot